### ISSUE TITLE
Strange error, but it works normally

### ISSUE THREAD

**Issue by zsw111-zzz** [TXH-mercury/VALOR#9]
Thank you very much for your excellent contribution,But I found some problems while running:During training or inference, the program repeatedly warns as follows, but the program still runs:

torch.cat(): Sizes of tensors must match except in dimension 0. Got 240 and 224 in dimension 2 (The offending index is 3)
05/17/2023 20:37:16 - INFO - __main__ -   current idx video7812 from ret returns wrong image/video, use 4266 instead.
torch.cat(): Sizes of tensors must match except in dimension 0. Got 240 and 224 in dimension 2 (The offending index is 3)
05/17/2023 20:37:17 - INFO - __main__ -   current idx video3481 from ret returns wrong image/video, use 225 instead.

**Comment by TXH-mercury** [comment]
hi @zsw111-zzz , this mechanism ensures that if there are errors when loading some broken examples (videos, images, or audios), another example will be sampled to replace it instead of whole program crushing (try-except). And you can remove it by filtering save examples in advance.  The information printed is the specific error in loading.  
In principle, this mechanism should only be used for training dataloader instead of test dataloader. And we have not remove it for test due to that almost all test datasets are not broken. (Most broken examples are in pretraining dataset.)

**Comment by zsw111-zzz** [comment]
Thank you very much for your reply. Your reply perfectly solved my problem. Thank you again for your outstanding contribution!
